/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.novicap.checkout;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CheckoutTest {

}
