/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.novicap.checkout;

import com.novicap.checkout.model.Discount;
import com.novicap.checkout.model.ProductCode;
import com.novicap.checkout.service.ShoppingService;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class Checkout {

    private final ShoppingService shoppingService;

    /**
     * Creates a new checkout with discount rules
     */
    public Checkout(List<Discount> discounts) {
        shoppingService = new ShoppingService(discounts);
    }

    /**
     * Creates a new checkout without discount rules
     */
    public Checkout() {
        List<Discount> discounts = new ArrayList<>();
        shoppingService = new ShoppingService(discounts);
    }

    public void scan(ProductCode productCode) {
        shoppingService.addProductToBasket(productCode);
    }

    public BigDecimal total() {
        return shoppingService.calculateTotal();
    }
}
