/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.novicap.checkout;

import com.novicap.checkout.model.Discount;
import com.novicap.checkout.model.ProductCode;
import com.novicap.checkout.service.ShoppingBasketService;

import java.math.BigDecimal;
import java.util.Map;

public class Checkout {

    private final ShoppingBasketService shoppingBasketService;

    public Checkout(Map<ProductCode, Discount> priceRules) {
        shoppingBasketService = new ShoppingBasketService(priceRules);
    }

    public void scan(ProductCode productCode) {
        shoppingBasketService.addProductToBasket(productCode);
    }

    public BigDecimal total() {
        return shoppingBasketService.calculateTotal();
    }
}
